/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VsIndexRouteImport } from './routes/vs.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as VsPermitRouteImport } from './routes/vs.permit'
import { Route as VsCaslRouteImport } from './routes/vs.casl'
import { Route as VsCasbinRouteImport } from './routes/vs.casbin'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsIndexRoute = VsIndexRouteImport.update({
  id: '/vs/',
  path: '/vs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsPermitRoute = VsPermitRouteImport.update({
  id: '/vs/permit',
  path: '/vs/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCaslRoute = VsCaslRouteImport.update({
  id: '/vs/casl',
  path: '/vs/casl',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCasbinRoute = VsCasbinRouteImport.update({
  id: '/vs/casbin',
  path: '/vs/casbin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/docs/getting-started',
  path: '/docs/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/vs/casbin': typeof VsCasbinRoute
  '/vs/casl': typeof VsCaslRoute
  '/vs/permit': typeof VsPermitRoute
  '/docs/': typeof DocsIndexRoute
  '/vs/': typeof VsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/vs/casbin': typeof VsCasbinRoute
  '/vs/casl': typeof VsCaslRoute
  '/vs/permit': typeof VsPermitRoute
  '/docs': typeof DocsIndexRoute
  '/vs': typeof VsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/vs/casbin': typeof VsCasbinRoute
  '/vs/casl': typeof VsCaslRoute
  '/vs/permit': typeof VsPermitRoute
  '/docs/': typeof DocsIndexRoute
  '/vs/': typeof VsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/getting-started'
    | '/vs/casbin'
    | '/vs/casl'
    | '/vs/permit'
    | '/docs/'
    | '/vs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/getting-started'
    | '/vs/casbin'
    | '/vs/casl'
    | '/vs/permit'
    | '/docs'
    | '/vs'
  id:
    | '__root__'
    | '/'
    | '/docs/getting-started'
    | '/vs/casbin'
    | '/vs/casl'
    | '/vs/permit'
    | '/docs/'
    | '/vs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  VsCasbinRoute: typeof VsCasbinRoute
  VsCaslRoute: typeof VsCaslRoute
  VsPermitRoute: typeof VsPermitRoute
  DocsIndexRoute: typeof DocsIndexRoute
  VsIndexRoute: typeof VsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/': {
      id: '/vs/'
      path: '/vs'
      fullPath: '/vs/'
      preLoaderRoute: typeof VsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/permit': {
      id: '/vs/permit'
      path: '/vs/permit'
      fullPath: '/vs/permit'
      preLoaderRoute: typeof VsPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/casl': {
      id: '/vs/casl'
      path: '/vs/casl'
      fullPath: '/vs/casl'
      preLoaderRoute: typeof VsCaslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/casbin': {
      id: '/vs/casbin'
      path: '/vs/casbin'
      fullPath: '/vs/casbin'
      preLoaderRoute: typeof VsCasbinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  VsCasbinRoute: VsCasbinRoute,
  VsCaslRoute: VsCaslRoute,
  VsPermitRoute: VsPermitRoute,
  DocsIndexRoute: DocsIndexRoute,
  VsIndexRoute: VsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
